### PR TITLE
Provide dispatch and lastAction parameters to errorHandler

### LINKED ISSUE #4: Thoughts on providing dispatch and the current action as arguments to the errorHandler?
This looks like a really useful tool for catching and logging errors inside reducers.

I'm just wondering if it breaks convention massively if the errorHandler function were able to dispatch an action that the app could pick up - like displaying a warning, or so on?

Something along the lines of this:

```js
import reduxCatch from 'redux-catch';
const errorHandler = (error, getState, dispatch, lastAction) => {
    console.error(error);
    dispatch({
        type: APP_UNKNOWN_ERROR,
        payload: {
            lastAction
        }
    });
};
const middleware = [reduxCatch(errorHandler)];
return createStore(
    rootReducer,
    initialState,
    compose(
        applyMiddleware(...middleware),
    )
); 
```

Thanks for writing this middleware!

### PR DESCRIPTION
**Pull request by willmorgan**
Fixes #4

### CODE REVIEW

**Comment by sergiodxa** [comment]
I like this. I'm only going to ask you for one change.

Can you change the order of `dispatch` and `lastAction`?

I think is more useful to have the dispatched action than the dispatcher function and if you change the order then you can use the `action `without defining `dispatch`.

**Comment by sergiodxa** [comment]
Forget it, I'm merging it, it's really simple the change so I will do it and publish it :)

**Comment by willmorgan** [comment]
Ahh thanks for taking this in @sergiodxa! I would have actioned your comment had I not been fast asleep 😴

**Comment by sergiodxa** [comment]
Don't worry, I just couldn't wait to merge and publish it :) It's already in npm as `v1.3.0`

**Pull request merged**
